blank_issues_enabled: false
contact_links: []
issue_templates:
- name: âœï¸ New Content Entry
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=content.yml
- name: ğŸ› ï¸ Refactor / Improve Structure
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=refactor.yml
- name: ğŸª² Bug Report
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=bug.yml
- name: ğŸŒŸ Feature Request
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=feature-request.yml
- name: ğŸ§¹ Project Cleanup
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=cleanup.yml
- name: ğŸ§ª Experiment / Test Log
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=test.yml
- name: ğŸ§­ Documentation Task
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=documentation.yml
- name: ğŸ¯ Goal Planning
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=goal-planning.yml
- name: ğŸ’¡ Idea / Brainstorm
  url: /PtiCalin/Awesome-Test-Vault/issues/new?template=general.yml
